CREATE TABLE ACTORS (
    ANAME VARCHAR(25),
    ANO VARCHAR(9), 
    PRIMARY KEY(ANO)
);

CREATE TABLE MOVIES (
    MNAME VARCHAR(30),
    MNO VARCHAR(6),
    PRIMARY KEY (MNO)
);

CREATE TABLE PLAY (
    ANO VARCHAR(9),  
    MNO VARCHAR(6),
    Payment INTEGER,
    FOREIGN KEY (ANO) REFERENCES ACTORS(ANO),
    FOREIGN KEY (MNO) REFERENCES MOVIES(MNO)
);

INSERT INTO ACTORS VALUES('L Grassy', 'A1');
INSERT INTO ACTORS VALUES('D Flower', 'A2');
INSERT INTO ACTORS VALUES('M Trunk', 'A3');
INSERT INTO ACTORS VALUES('J Swanson', 'A4');
INSERT INTO ACTORS VALUES('T Branch', 'A5');
INSERT INTO ACTORS VALUES('L Leafy', 'A6');


INSERT INTO MOVIES VALUES('Long walk', 'M1');
INSERT INTO MOVIES VALUES('Longest day', 'M2');
INSERT INTO MOVIES VALUES('Love the fun', 'M3');
INSERT INTO MOVIES VALUES('Laugh and cry', 'M4');

INSERT INTO PLAY VALUES('A1', 'M1', 78);
INSERT INTO PLAY VALUES('A1', 'M2', 80);
INSERT INTO PLAY VALUES('A2', 'M2', 83);
INSERT INTO PLAY VALUES('A2', 'M3', 88);
INSERT INTO PLAY VALUES('A2', 'M4', 86);
INSERT INTO PLAY VALUES('A3', 'M2', 74);
INSERT INTO PLAY VALUES('A3', 'M3', 89);
INSERT INTO PLAY VALUES('A4', 'M2', 75);
INSERT INTO PLAY VALUES('A4', 'M3', 85);
INSERT INTO PLAY VALUES('A4', 'M4', 55);
INSERT INTO PLAY VALUES('A5', 'M1', 58);
INSERT INTO PLAY VALUES('A5', 'M3', 56);
INSERT INTO PLAY VALUES('A5', 'M4', 55);
INSERT INTO PLAY VALUES('A6', 'M2', 77);
INSERT INTO PLAY VALUES('A6', 'M3', 88);
INSERT INTO PLAY VALUES('A6', 'M4', 54);

DROP TABLE ACTORS;
DROP TABLE MOVIES;
DROP TABLE PLAY;
SELECT * FROM ACTORS;
SELECT * FROM MOVIES;
SELECT * FROM PLAY;

SELECT ANAME
FROM ACTORS
WHERE ANO NOT IN 
(SELECT ANO
FROM PLAY
WHERE MNO IN
(SELECT P.MNO
FROM PLAY P
INNER JOIN ACTORS A
ON P.ANO = A.ANO
WHERE A.ANAME = 'J Swanson'));

SELECT M.MNAME
FROM PLAY P
INNER JOIN ACTORS A
ON P.ANO = A.ANO
INNER JOIN MOVIES M
ON P.MNO = M.MNO
WHERE A.ANAME = 'J Swanson'
AND M.MNO IN
(SELECT M.MNO
FROM PLAY P
INNER JOIN ACTORS A 
ON P.ANO = A.ANO
INNER JOIN MOVIES M
ON P.MNO = M.MNO        
WHERE A.ANAME = 'T Branch');

SELECT DISTINCT A.ANAME 
FROM ACTORS A 
INNER JOIN PLAY P
ON A.ANO = P.ANO
WHERE P.Payment > ALL 
( SELECT P.Payment
FROM ACTORS A INNER JOIN PLAY P
ON A.ANO = P.ANO
WHERE A.ANAME = 'J Swanson');

SELECT DISTINCT M.MNO, 
AVG(P.Payment), 
COUNT(DISTINCT P.ANO) 
FROM MOVIES M 
JOIN Play P 
ON M.MNO = P.MNO 
GROUP BY M.MNO;

SELECT TAB1.MNO, TAB1.AveragePayment, TAB1.NumberOfActors, TAB2.NumberOfActorsBelowAverage
FROM    
(SELECT M.MNO, AVG(P.Payment) AS AveragePayment, COUNT(A.ANO) AS NumberOfActors
FROM (( ACTORS A 
INNER JOIN PLAY P ON A.ANO = P.ANO)
INNER JOIN MOVIES M ON P.MNO = M.MNO)
GROUP BY M.MNO) TAB1,
(SELECT M.MNO, COUNT(P.ANO) AS NumberOfActorsBelowAverage
FROM MOVIES M 
INNER JOIN PLAY P ON M.MNO = P.MNO
WHERE P.Payment <  
(SELECT AVG(P.Payment) 
FROM MOVIES M2 
INNER JOIN PLAY P ON M2.MNO = P.MNO
WHERE M2.MNO = M.MNO
GROUP BY M2.MNO)
GROUP BY M.MNO) TAB2
WHERE TAB1.MNO = TAB2.MNO;

SELECT A.ANAME, AVG(P.Payment) AS AveragePayment
FROM ACTORS A INNER JOIN Play P
ON A.ANO = P.ANO
GROUP BY A.ANAME;

SELECT A.ANAME, AVG(P.Payment) AS AveragePayment
FROM ACTORS A INNER JOIN PLAY P
ON A.ANO = P.ANO
GROUP BY A.ANO, A.ANAME
HAVING AVG(P.Payment) = 
(SELECT MAX(TAB1.AveragePayment)
FROM (SELECT P.ANO, AVG(P.Payment) AS AveragePayment
FROM PLAY P
GROUP BY P.ANO
) TAB1);

